### ISSUE TITLE
关于远程日志问题

### ISSUE THREAD

**Issue by swimmingchar** [olajowon/loggrove#1]
您好，远程您是通过monitor推送，您的monitor.py 在哪里啊？这个也需要python3版本么？

**Comment by olajowon** [comment]
monitor.py 是执行 build.py 后生成的，monitor.py 还是用于监控、统计、告警的，不用于阅读日志，阅读远程日志是 handlers/read.py  和 handlers/keepread.py

**Comment by swimmingchar** [comment]
好的，非常感谢，我本地部署一下试一试，万分感谢分享这么好的东东。
