### ISSUE TITLE
日志文件添加

### ISSUE THREAD

**Issue by VinnyWan** [olajowon/loggrove#10]
你好，我再添加日志文件的时候，hosts的时候有疑问。添加成功之后，查询日志文件的时候提示
GET paths error：{"code": 500, "msg": "Query failed", "detail": "[Errno 2] No such file or directory: ''"}
但是，host我写的是IP地址（同时也尝试了主机名），均为相同保存。是我填写的有问题吗？还是有特殊的要求

**Comment by olajowon** [comment]
应该是你的 settings ssh 公钥文件路径配置有问题，需要配绝对路径

**Comment by VinnyWan** [comment]
你好，我是用的不是ssh公钥哦，使用的是统一密码登录的

**Comment by VinnyWan** [comment]
但是我刚刚测试使用localhost是成功了，感觉这个ssh接口是不是写的有问题？

**Comment by olajowon** [comment]
如果密码登录，就直接把SSH.key_filepath这个键值对删了；localhost是不走ssh的

**Comment by VinnyWan** [comment]
好的我试试

**Comment by VinnyWan** [comment]
你好，测试OK，谢谢大佬的指定，给您点个star

**Comment by olajowon** [comment]
😁

**Comment by VinnyWan** [comment]
你好，使用秘钥解决了这个问题。建议在代码里面加个判断，如果key为空值。使用密码登录。嘿嘿 。这样会更人性化一点。
另外在麻烦您一下。就是实时阅读的时候出现了报错。提示是这个
Connection ...
Connection error ...
Connection closed ...

最后就没有消息了。我看demo上是直接显示出来连接成功。但是我这个不确定是哪里出现了问题

**Comment by olajowon** [comment]
可以看下日志

**Comment by VinnyWan** [comment]
{"datetime":"2020-04-20 13:42:53", "module":"web", "lineno":"2106", "level":"WARNING", "message":"400 GET /keepread/?logfile=server&match=&host=192.168.2.199&path=/data/log/server/stdout.log (192.168.2.180) 2.04ms"}
这个就是对应的日志，我这个文件命名是存在的，并且在分页阅读上是能够被检索的

**Comment by olajowon** [comment]
你是用的nginx 转发的？看看你的nginx 转发规则是否支持websocket

**Comment by VinnyWan** [comment]
多谢  果然是这个问题。
