### ISSUE TITLE
实时阅读问题

### ISSUE THREAD

**Issue by VinnyWan** [olajowon/loggrove#12]
你好，能请教下。因为一个服务是多节点的，当我打开一个节点的实时查看日志，就不能再同时打开另外一个节点的实时日志进行查看，这个时候上一个节点就会直接断开。能不能同时打开2个以上的实时查看呢？

**Comment by VinnyWan** [comment]
我看代码里面是支持多线程操作的。但是这个我打开一个实时阅读的节点。然后就关闭一个节点，这个和多线程的概念不相同的。
Error [Code: 403] New connection has been opened, and this connection needs to be closed

**Comment by olajowon** [comment]
https://github.com/olajowon/loggrove/blob/3b5f596eb7e5d2a72119d3909b593961dacecef1/handlers/keepread.py#L59 在这里限制了一个用户只能开启已个通道，已经忘了当时为啥这么做，如果不想这么限制，直接把59-64行注释了就可以

**Comment by VinnyWan** [comment]
好的 测试是OK的。多谢大佬哇
