### ISSUE TITLE
怎样连接像阿里云这样的远程的服务器？

### ISSUE THREAD

**Issue by huxxhua** [olajowon/loggrove#17]
配置好了，选主机地址时提示：
GET paths error：{"code": 500, "msg": "Query failed", "detail": "[Errno 101] Network is unreachable"}

![image](https://user-images.githubusercontent.com/20944512/105468761-4d051b80-5cd2-11eb-83db-376f9dfce623.png)

**Comment by olajowon** [comment]
配置一下 settings SSH key_filename="私钥路径"

**Comment by huxxhua** [comment]
@olajowon 
谢谢大佬，是网络问题，已经解决！

还有一个问题想请教的
监控项那块怎么弄的，弄了一下还是没有数据？
已经运行起来monitor.py了

日志返回：
{"datetime":"2021-01-22 17:32:00", "lineno":"168", "name":"root", "level":"ERROR", "message":"Monitor error, 2021-01-22 17:32, 申报平台, , [Errno 2] No such file or directory: ''"}

猜想是不是因为文件路径 带*的正则，就匹配不到路径了，只能单个文件的统计统计？
因为存在一个目录下会有多个文件，
不知道有没有理解错。
![image](https://user-images.githubusercontent.com/20944512/105475854-d587ba00-5cda-11eb-81d3-54da0a34995c.png)

**Comment by olajowon** [comment]
monitor.py 要在日志实际的机器上运行

**Comment by huxxhua** [comment]
@olajowon 明白，我再试试
