### ISSUE TITLE
配置成功，但登录失败

### ISSUE THREAD

**Issue by WANGDADAYA** [olajowon/loggrove#19]
![image](https://user-images.githubusercontent.com/59329404/110117861-70a0a300-7df4-11eb-8dfa-2fe3e3fc8418.png)
![image](https://user-images.githubusercontent.com/59329404/110117914-86ae6380-7df4-11eb-87ed-19f06a4e4997.png)
您好，配置成功了  ，用这个超级管理员登录怎么会是登陆失败呢？谢谢您抽时间解答。

**Comment by olajowon** [comment]
看看log有没有什么提示

**Comment by WANGDADAYA** [comment]
![image](https://user-images.githubusercontent.com/59329404/110284579-facb5000-801c-11eb-8d28-b7119244d802.png)

**Comment by olajowon** [comment]
/tmp/loggrove.log 里头呢

**Comment by WANGDADAYA** [comment]
module 'pymysql' has no attribute 'escape_string'
