### ISSUE TITLE
权限相关问题

### ISSUE THREAD

**Issue by swimmingchar** [olajowon/loggrove#2]
您好，这个程序附带权限有什么思路么？另外关于远程日志，会将日志保存至本地么？

**Comment by olajowon** [comment]
这个权限是指用户对程序内资源增删改的权限；
目前支持对远程机器上日志进行 分页阅读、实时阅读、实时收集统计数、实时监控告警等，暂时没有收集远程全量日志至本地的功能

**Comment by swimmingchar** [comment]
举个栗子，我们这边有77个应用，但是有规定一个组的人只能看他们自己组应用的日志，其他应用日志不能看。

**Comment by olajowon** [comment]
这方面的权限目前还不支持，在不断完善核心功能后，会考虑更细致的权限管理

**Comment by swimmingchar** [comment]
非常感谢。
