### ISSUE TITLE
请问根据日期生成的日志如何更新自动更新查看文件

### ISSUE THREAD

**Issue by excxapp** [olajowon/loggrove#4]
我们的日志是根据日期生成的。请问每次都要完整的日志文件名称吗？

比如可以根据所在目录进行查看吗

![image](https://user-images.githubusercontent.com/4355581/57602459-b80bce80-7591-11e9-94cb-f68049231ccc.png)

**Comment by olajowon** [comment]
目前暂不支持根据目录查看；每日按日期新增的日志，需要写个daemon 定时写入系统
