### ISSUE TITLE
统计无法上报，作者大人 看看呗

### ISSUE THREAD

**Issue by a290013130** [olajowon/loggrove#5]
统计无法上报，作者大人 看看呗

**Comment by olajowon** [comment]
大兄弟，重新pull下最新的代码，之前build有bug 😳

**Comment by a290013130** [comment]
去掉了crontab ?? 不用定时任务了？

**Comment by a290013130** [comment]
还是 不能获取到  监控统计。

**Comment by a290013130** [comment]
{"code": 200, "msg": "Query successful", "data": {"series": [{"name": "LogMonitor-localhost-Login", "data": []}, {"name": "LogMonitor-localhost-Total", "data": []}], "xAxis": {"min": 1569754500000.0, "max": 1569840900000.0}}}      data 里面是空的   数据库里面也没有

**Comment by olajowon** [comment]
不用定时任务了，readme 里有 monitor 的启动方法

**Comment by a290013130** [comment]
被监控的机器 就不用在运行monitor 了 对吧  只要主机里面增加这个？

**Comment by a290013130** [comment]
还有为啥 时间少3分钟。监控数据

**Comment by olajowon** [comment]
每一台远程机器上都要单独跑monitor，统计、检查、报警都是在各个节点机上完成的。
时间少3分钟是什么问题？没大明白

**Comment by a290013130** [comment]
依次点开 日志图表  然后查询 最近1个小时。    看下面的趋势图。。。你会发现。。。最近一小时  缺少了 3分钟的数据。

**Comment by olajowon** [comment]
最后的一两分钟？那个是因为统计、检查、上报延迟导致的

**Comment by a290013130** [comment]
这个要该哪里才能将误差  降低到最少。

**Comment by olajowon** [comment]
如果时间差大于2分钟，应该是浏览器时间和服务器时间差别比较大导致的。像浏览器已经到 5分了，而服务器还是2分，这时候查最近一小时，其实是根据浏览器时间的最近一小时，所以最终从服务器查出来的数据时间差会比较大

**Comment by a290013130** [comment]
那为什么会数据库里的时间也是一样差3分钟呢。。想不明白。

**Comment by a290013130** [comment]
有空整个 对接 sso  单点登录呗
