### ISSUE TITLE
ldap方式登录第二次登录会报错

### ISSUE THREAD

**Issue by jaygarrison94** [olajowon/loggrove#7]
数据库操作会报  “%d format: a number is required, not str”

看了下updatesql = 'UPDATE user SET username=%s, password=%s, email=%s WHERE id=%d'

查了下资料：解决方案：The format string is not really a normal Python format string. Youmust always use %s for all fields. 也就是MySQLdb的字符串格式化不是标准的python的字符串格式化,应当一直使用%s用于字符串格式化
将id=%d  改为 id=%s就好了
不知作者有没有出现过这种情况

**Comment by olajowon** [comment]
感谢老哥提的bug
